- name: Test minimal playbook
  hosts: all
  tasks:
    - name: Ensure python3 is present
      ansible.builtin.raw: dnf install -y python3
      changed_when: false
      register: python_check
      until: python_check.rc == 0
      retries: 3
      delay: 5