---
  el:
    hosts:
      centos7:
        ansible_connection: docker
  deb:
    hosts:
      debian-python:
        ansible_connection: docker
  local:
    hosts:
      localhost:
        ansible_connection: local
  fed:
    hosts:
      fedora:
        ansible_connection: local