---
clickhouse:
  hosts:
    clickhouse-1:
      ansible_host: 84.252.134.203

vector:
  hosts:
    vector-01:
      ansible_host: 51.250.44.130

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.154.52